### ISSUE TITLE
Updated to pylexibank 2.0

### ISSUE THREAD

**Issue by chrzyki** [intercontinental-dictionary-series/ids#7]
See here: https://github.com/lexibank/ids/commit/9c5f7a818bade30c7fb40bdab0b49097f70761eb

I'm not yet sure whether we should touch the IDs (parameters, languages), given the dataset's source.

**Comment by tresoldi** [comment]
I am having a similar issue. Did we decide about a default for IDs, after all, considering readability, uniqueness, etc.?

**Comment by chrzyki** [comment]
More or less, yeah. Languages ideally in CamelCase and parameters as:

```python
concepts = args.writer.add_concepts(
    id_factory=lambda c: c.id.split('-')[-1] + '_' + slug(c.english), lookup_factory="Name"
)
```

**Comment by LinguList** [comment]
The basic rationale here is: if you have an ID for a concept, this ID is supposed to be unique, as guaranteed by concepticon. So if you just use that ID, which is the last number in a concept list, this is fine, but this would prevent readability, so the slugging is extra for readability only. If you want to preserve the ID in the source, overwrite the concepts or the lexeme class even. See e.g., `suntb`, where I add the `STEDT_RN` as lexeme ID since this is useful, as it links to the STEDT website.

**Comment by chrzyki** [comment]
Done
